In [1]:
import numpy as np

In [2]:
class Sigmoid:
    def __init__(self):
        self.params = []
    
    def forward(self,x):
        return 1/(1+np.exp(-x))

In [3]:
class Affine:
    def __init__(self, W, b):
        self.params = [W,b]
        
    def forward(self,x):
        W, b = self.params
        out = np.matmul(x,W) + b
        return out

In [6]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        # 가중치와 편향 초기화
        W1 = np.random.rand(I,H)
        b1 = np.random.rand(H)
        W2 = np.random.rand(H,O)
        b2 = np.random.rand(O)
        
        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        
        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layer in self.layers:
            self.params += layer.params
        
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [7]:
x = np.random.rand(10,2)
model = TwoLayerNet(2,4,3)
s = model.predict(x)

In [8]:
model.params

[array([[0.17995406, 0.37064927, 0.7871928 , 0.78928894],
        [0.20296346, 0.78655393, 0.42595637, 0.43823204]]),
 array([0.11603309, 0.2671896 , 0.10623138, 0.04552917]),
 array([[0.68516979, 0.95591099, 0.60258846],
        [0.97196543, 0.16117251, 0.763634  ],
        [0.6176162 , 0.51217923, 0.49488128],
        [0.54004689, 0.06849005, 0.59835616]]),
 array([0.27790205, 0.88103232, 0.28915997])]