In [15]:
import numpy as np

In [16]:
idx = np.random.permutation(5)
print(idx)

[0 2 3 4 1]


In [17]:
arr = np.random.rand(5)

In [18]:
print(arr)

[0.32046606 0.19071477 0.70916124 0.70245556 0.96154695]


In [19]:
arr = arr[idx]

In [20]:
print(arr)

[0.32046606 0.70916124 0.70245556 0.96154695 0.19071477]


In [21]:
a = np.random.rand(3)
print(a.dtype)

float64


In [22]:
a = np.random.rand(3).astype('f')
print(a.dtype)

float32
